language: go

go:
  - 1.13.x

script:
  # build test for supported platforms
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOOS=windows go build
  - GOOS=js GOARCH=wasm go build

  # run TestPublicKeyDecompression one hundred times
  - go test -v -run TestPublicKeyDecompression -count 100

  # run tests on a standard platform
  - go test -v ./...

  # run tests with the race detector as well
  - go test -race -v ./...