name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: GOOS=linux go build

    - name: WASM Build
      run: GOOS=js GOARCH=wasm go build

    - name: Test decompression
      run: go test -v -run TestPublicKeyDecompression -count 100

    - name: Test
      run: go test -v ./...

    - name: Test race
      run: go test -race -v ./...
